"use client";
import {useEffect,useMemo,useRef,useState} from "react";
import {catalogGames,catalogGenres,type CatalogGame} from "./games";
import ShadowHouse from "./ShadowHouseReal";
const MAZE=["111111111111","100000100001","101110101101","100010100001","111010111101","100010000001","101111011101","100001010001","101101010111","100100010001","100001000001","111111111111"];
type Leader={name:string;time:number}|null;
const clean=(v:string)=>v.trim().replace(/[<>]/g,"").slice(0,18)||"بازیکن ناشناس";
type Lang="fa"|"en";
type Theme="purple"|"blue"|"green"|"orange"|"mono"|"light";
const genreEn:Record<string,string>={"همه":"All","اکشن":"Action","نقش‌آفرینی":"RPG","تیراندازی":"Shooter","استراتژی":"Strategy","مستقل":"Indie","شبیه‌سازی":"Simulation","ترس و معما":"Horror & Puzzle","مسابقه‌ای و ورزشی":"Racing & Sports","بقا و جهان‌باز":"Survival & Open World","ماجراجویی و گروهی":"Adventure & Party"};
const gameText={fa:{leader:"♛ رکورد نفر اول",empty:"هنوز رکوردی ثبت نشده",keys:"کلیدها",clock:"زمان",shrink:"کوچک‌نمایی",expand:"⛶ بزرگ‌نمایی",lost:"نگهبان پیدایت کرد!",won:"از خانه فرار کردی!",title:"خانه سایه‌ها",intro:"سه کلید را پیدا کن، از نگهبان دور بمان و در خروج را باز کن.",winTime:"زمان فرار",player:"نام بازیکن",placeholder:"نامت را بنویس",enter:"ورود به خانه",retry:"تلاش دوباره",controls:"حرکت: W A S D • چرخش: ← → یا Q E",mission:"سه کلید را پیدا کن و به در خروج برس.",keyFound:"کلید پیدا شد! نگهبان کمی سریع‌تر شد...",seconds:"ثانیه"},en:{leader:"♛ TOP RECORD",empty:"No record yet",keys:"Keys",clock:"Time",shrink:"Exit fullscreen",expand:"⛶ Fullscreen",lost:"The guardian found you!",won:"You escaped the house!",title:"Shadow House",intro:"Find three hidden keys, avoid the guardian, and unlock the exit.",winTime:"Escape time",player:"Player name",placeholder:"Enter your name",enter:"Enter the house",retry:"Try again",controls:"Move: W A S D • Turn: ← → or Q E",mission:"Find all three keys and reach the exit.",keyFound:"Key found! The guardian is getting faster...",seconds:"seconds"}};

function LegacyShadowHouse({lang}:{lang:Lang}){
 const gt=gameText[lang];
 const canvasRef=useRef<HTMLCanvasElement>(null),shellRef=useRef<HTMLDivElement>(null),frameRef=useRef<number|null>(null),pressed=useRef<Record<string,boolean>>({});
 const state=useRef({running:false,p:{x:1.5,y:1.5,a:0},e:{x:9.5,y:1.5},items:[{x:3.5,y:3.5,got:false},{x:8.5,y:5.5,got:false},{x:2.5,y:9.5,got:false}],start:0,last:0});
 const [phase,setPhase]=useState<"intro"|"playing"|"lost"|"won">("intro"),[name,setName]=useState(""),[found,setFound]=useState(0),[time,setTime]=useState(0),[leader,setLeader]=useState<Leader>(null),[note,setNote]=useState(gt.mission),[full,setFull]=useState(false);
 const wall=(x:number,y:number)=>MAZE[Math.floor(y)]?.[Math.floor(x)]!=="0";
 const free=(x:number,y:number)=>!wall(x+.17,y)&&!wall(x-.17,y)&&!wall(x,y+.17)&&!wall(x,y-.17);
 const start=()=>{if(frameRef.current)cancelAnimationFrame(frameRef.current);pressed.current={};state.current={running:true,p:{x:1.5,y:1.5,a:0},e:{x:9.5,y:1.5},items:[{x:3.5,y:3.5,got:false},{x:8.5,y:5.5,got:false},{x:2.5,y:9.5,got:false}],start:performance.now(),last:performance.now()};setFound(0);setTime(0);setNote(gt.mission);setPhase("playing")};
 useEffect(()=>{try{const saved=localStorage.getItem("shadow-house-leader");if(saved)setLeader(JSON.parse(saved))}catch{localStorage.removeItem("shadow-house-leader")}const dn=(e:KeyboardEvent)=>{pressed.current[e.key.toLowerCase()]=true;if(["arrowup","arrowdown","arrowleft","arrowright"," "].includes(e.key.toLowerCase()))e.preventDefault()},up=(e:KeyboardEvent)=>pressed.current[e.key.toLowerCase()]=false,fs=()=>{if(document.fullscreenElement===shellRef.current)setFull(true);else setFull(false)},external=()=>start();addEventListener("keydown",dn);addEventListener("keyup",up);addEventListener("start-shadow-house",external);document.addEventListener("fullscreenchange",fs);return()=>{removeEventListener("keydown",dn);removeEventListener("keyup",up);removeEventListener("start-shadow-house",external);document.removeEventListener("fullscreenchange",fs)}},[lang]);
 useEffect(()=>{if(!full)return;const previous=document.body.style.overflow,shell=shellRef.current,esc=(e:KeyboardEvent)=>{if(e.key==="Escape"&&!document.fullscreenElement)setFull(false)};shell?.classList.add("expanded");document.body.style.overflow="hidden";addEventListener("keydown",esc);return()=>{shell?.classList.remove("expanded");document.body.style.overflow=previous;removeEventListener("keydown",esc)}},[full]);
 const finish=(won:boolean)=>{const s=state.current;s.running=false;const final=Math.floor((performance.now()-s.start)/1000);setTime(final);setPhase(won?"won":"lost");if(won&&(!leader||final<leader.time)){const next={name:clean(name),time:final};localStorage.setItem("shadow-house-leader",JSON.stringify(next));setLeader(next)}};
 const hold=(k:string,on:boolean)=>pressed.current[k]=on;
 const toggleFull=async()=>{if(full){setFull(false);if(document.fullscreenElement){try{await document.exitFullscreen()}catch{}}return}setFull(true);const shell=shellRef.current;if(!shell)return;try{if(shell.requestFullscreen)await shell.requestFullscreen()}catch{/* Keep the CSS fullscreen fallback active when native fullscreen is blocked. */}};
 useEffect(()=>{if(phase!=="playing")return;const canvas=canvasRef.current,ctx=canvas?.getContext("2d");if(!canvas||!ctx)return;const FOV=Math.PI/3;
  const sprite=(x:number,y:number,kind:"key"|"guard",depth:number[],w:number,h:number)=>{const s=state.current,p=s.p,dx=x-p.x,dy=y-p.y,d=Math.hypot(dx,dy);let a=Math.atan2(dy,dx)-p.a;while(a>Math.PI)a-=Math.PI*2;while(a< -Math.PI)a+=Math.PI*2;if(Math.abs(a)>FOV*.7||d<.2)return;const sx=w/2+Math.tan(a)/Math.tan(FOV/2)*w/2,col=Math.max(0,Math.min(depth.length-1,Math.floor(sx/w*depth.length)));if(d>depth[col]+.4)return;const size=Math.min(h*.82,h/d*(kind==="guard"?.92:.38));ctx.save();ctx.translate(sx,h/2+size*.18);
   if(kind==="key"){ctx.shadowBlur=25;ctx.shadowColor="#ffd45d";ctx.strokeStyle="#ffe58f";ctx.lineWidth=Math.max(2,size*.045);ctx.beginPath();ctx.arc(0,-size*.16,size*.15,0,Math.PI*2);ctx.moveTo(size*.15,-size*.16);ctx.lineTo(size*.46,-size*.16);ctx.lineTo(size*.46,size*.05);ctx.moveTo(size*.3,-size*.16);ctx.lineTo(size*.3,0);ctx.stroke()}
   else{ctx.shadowBlur=35;ctx.shadowColor="#9e2442";const g=ctx.createLinearGradient(0,-size/2,0,size/2);g.addColorStop(0,"#6e2338");g.addColorStop(1,"#10080d");ctx.fillStyle=g;ctx.beginPath();ctx.arc(0,-size*.33,size*.13,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.moveTo(-size*.18,-size*.2);ctx.lineTo(-size*.26,size*.45);ctx.lineTo(size*.26,size*.45);ctx.lineTo(size*.18,-size*.2);ctx.fill();ctx.fillStyle="#ff5270";ctx.beginPath();ctx.arc(-size*.05,-size*.35,Math.max(1.5,size*.013),0,Math.PI*2);ctx.arc(size*.05,-size*.35,Math.max(1.5,size*.013),0,Math.PI*2);ctx.fill()}ctx.restore()};
  const render=(now:number)=>{const s=state.current;if(!s.running)return;const rect=canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,1.5);if(canvas.width!==Math.floor(rect.width*dpr)||canvas.height!==Math.floor(rect.height*dpr)){canvas.width=Math.floor(rect.width*dpr);canvas.height=Math.floor(rect.height*dpr)}ctx.setTransform(dpr,0,0,dpr,0,0);const w=rect.width,h=rect.height,dt=Math.min((now-s.last)/1000,.04);s.last=now;const p=s.p,turn=1.8*dt,move=1.9*dt;if(pressed.current.arrowleft||pressed.current.q)p.a-=turn;if(pressed.current.arrowright||pressed.current.e)p.a+=turn;const f=(pressed.current.w||pressed.current.arrowup?1:0)-(pressed.current.s||pressed.current.arrowdown?1:0),st=(pressed.current.d?1:0)-(pressed.current.a?1:0),nx=p.x+(Math.cos(p.a)*f+Math.cos(p.a+Math.PI/2)*st)*move,ny=p.y+(Math.sin(p.a)*f+Math.sin(p.a+Math.PI/2)*st)*move;if(free(nx,p.y))p.x=nx;if(free(p.x,ny))p.y=ny;
   const e=s.e,ed=Math.hypot(p.x-e.x,p.y-e.y),got=s.items.filter(i=>i.got).length;if(ed<8.5){const es=(.48+got*.09)*dt,ex=e.x+(p.x-e.x)/ed*es,ey=e.y+(p.y-e.y)/ed*es;if(free(ex,e.y))e.x=ex;if(free(e.x,ey))e.y=ey}if(ed<.48){finish(false);return}s.items.forEach(i=>{if(!i.got&&Math.hypot(p.x-i.x,p.y-i.y)<.42){i.got=true;setNote(gt.keyFound)}});const total=s.items.filter(i=>i.got).length;if(total!==got||total!==found)setFound(total);if(total===3&&Math.hypot(p.x-10.35,p.y-10.35)<.75){finish(true);return}setTime(Math.floor((now-s.start)/1000));
   const c=ctx.createLinearGradient(0,0,0,h/2);c.addColorStop(0,"#020306");c.addColorStop(1,"#151923");ctx.fillStyle=c;ctx.fillRect(0,0,w,h/2);const fl=ctx.createLinearGradient(0,h/2,0,h);fl.addColorStop(0,"#14151a");fl.addColorStop(1,"#030405");ctx.fillStyle=fl;ctx.fillRect(0,h/2,w,h/2);const rays=Math.min(420,Math.floor(w/2)),depth:number[]=[];for(let i=0;i<rays;i++){const ra=p.a-FOV/2+i/rays*FOV;let d=.02,hx=0,hy=0;while(d<16){hx=p.x+Math.cos(ra)*d;hy=p.y+Math.sin(ra)*d;if(wall(hx,hy))break;d+=.035}const cor=d*Math.cos(ra-p.a);depth.push(cor);const wh=Math.min(h*1.7,h/Math.max(.15,cor)*.78),shade=Math.max(18,116-cor*12),side=Math.abs((hx%1)-.5)>Math.abs((hy%1)-.5)?.78:1;ctx.fillStyle=`rgb(${shade*side},${(shade+7)*side},${(shade+13)*side})`;ctx.fillRect(i*w/rays,h/2-wh/2,w/rays+1,wh)}s.items.filter(i=>!i.got).forEach(i=>sprite(i.x,i.y,"key",depth,w,h));sprite(e.x,e.y,"guard",depth,w,h);if(total===3)sprite(10.35,10.35,"key",depth,w,h);const v=ctx.createRadialGradient(w/2,h/2,h*.08,w/2,h/2,h*.7);v.addColorStop(0,"rgba(0,0,0,0)");v.addColorStop(.58,"rgba(0,0,0,.08)");v.addColorStop(1,"rgba(0,0,0,.94)");ctx.fillStyle=v;ctx.fillRect(0,0,w,h);ctx.strokeStyle="rgba(255,255,255,.45)";ctx.beginPath();ctx.moveTo(w/2-8,h/2);ctx.lineTo(w/2+8,h/2);ctx.moveTo(w/2,h/2-8);ctx.lineTo(w/2,h/2+8);ctx.stroke();frameRef.current=requestAnimationFrame(render)};frameRef.current=requestAnimationFrame(render);return()=>{if(frameRef.current)cancelAnimationFrame(frameRef.current)}},[phase]);
 return <div className="haunted" ref={shellRef} dir={lang==="fa"?"rtl":"ltr"}><div className="gamebar"><div className="leader"><span>{gt.leader}</span>{leader?<b>{leader.name} — {leader.time.toLocaleString(lang==="fa"?"fa-IR":"en-US")} {gt.seconds}</b>:<b>{gt.empty}</b>}</div><div className="mission"><span>{gt.keys} <b>{found.toLocaleString(lang==="fa"?"fa-IR":"en-US")} / 3</b></span><span>{gt.clock} <b>{time.toLocaleString(lang==="fa"?"fa-IR":"en-US")}</b></span></div><button type="button" onClick={toggleFull}>{full?gt.shrink:gt.expand}</button></div><div className="gameview"><canvas ref={canvasRef} aria-label="Shadow House 3D game"/>{phase!=="playing"&&<div className="startlayer"><span className="door">⌂</span><small>SHADOW HOUSE 3D</small><h3>{phase==="lost"?gt.lost:phase==="won"?gt.won:gt.title}</h3><p>{phase==="won"?`${gt.winTime}: ${time.toLocaleString(lang==="fa"?"fa-IR":"en-US")} ${gt.seconds}`:gt.intro}</p><label>{gt.player}<input value={name} onChange={e=>setName(e.target.value)} maxLength={18} placeholder={gt.placeholder}/></label><button type="button" onClick={start}>{phase==="intro"?gt.enter:gt.retry}</button><em>{gt.controls}</em></div>}{phase==="playing"&&<div className="gamenote">{note}</div>}</div><div className="touch" dir="ltr"><button type="button" onPointerDown={()=>hold("q",true)} onPointerUp={()=>hold("q",false)} onPointerCancel={()=>hold("q",false)}>↶</button><div><button type="button" onPointerDown={()=>hold("w",true)} onPointerUp={()=>hold("w",false)} onPointerCancel={()=>hold("w",false)}>↑</button><span><button type="button" onPointerDown={()=>hold("a",true)} onPointerUp={()=>hold("a",false)} onPointerCancel={()=>hold("a",false)}>←</button><button type="button" onPointerDown={()=>hold("s",true)} onPointerUp={()=>hold("s",false)} onPointerCancel={()=>hold("s",false)}>↓</button><button type="button" onPointerDown={()=>hold("d",true)} onPointerUp={()=>hold("d",false)} onPointerCancel={()=>hold("d",false)}>→</button></span></div><button type="button" onPointerDown={()=>hold("e",true)} onPointerUp={()=>hold("e",false)} onPointerCancel={()=>hold("e",false)}>↷</button></div></div>
}

function Card({g,fav,toggle,open,lang}:{g:CatalogGame;fav:boolean;toggle:()=>void;open:()=>void;lang:Lang}){
 const en=lang==="en",initials=g.title.split(/\s+/).slice(0,2).map(x=>x[0]).join(""),rank=[...catalogGames].sort((a,b)=>b.score-a.score).findIndex(x=>x.id===g.id)+1;
 return <article className="card">
  <div className="poster" style={{"--c1":g.palette[0],"--c2":g.palette[1],"--r":`${(g.id%7)-3}deg`} as React.CSSProperties} role="img" aria-label={`${en?"Official artwork for":"تصویر رسمی بازی"} ${g.title}`}>
   <img className="official-cover" src={g.image} alt="" loading="lazy"/><i/><strong>{initials}</strong><span>{g.title}</span><b>#{rank.toLocaleString(en?"en-US":"fa-IR")}</b>
   <button type="button" aria-label={en?"Favorite":"علاقه‌مندی"} className={fav?"fav on":"fav"} onClick={toggle}>{fav?"♥":"♡"}</button>
  </div>
  <div className="cardbody"><div className="meta"><span>{en?genreEn[g.genre]:g.genre}</span><b>★ {g.score.toLocaleString(en?"en-US":"fa-IR")}</b></div><h3 dir="ltr">{g.title}</h3><p>{en?g.storyEn:g.description}</p><div className="chips"><span>{en?"Game modes":g.mode}</span><span>{en?"Selected title":g.difficulty}</span></div><button type="button" onClick={open}>{en?"Full details":"اطلاعات کامل"} <span>←</span></button></div>
 </article>
}

export default function Home(){
 const[q,setQ]=useState(""),[genre,setGenre]=useState("همه"),[visible,setVisible]=useState(20),[favs,setFavs]=useState<number[]>([]),[only,setOnly]=useState(false),[selected,setSelected]=useState<CatalogGame|null>(null),[lang,setLang]=useState<Lang>("fa"),[theme,setTheme]=useState<Theme>("purple"),[accountName,setAccountName]=useState("");
 const en=lang==="en";
 useEffect(()=>{try{const s=localStorage.getItem("gameverse-200-favorites");if(s)setFavs(JSON.parse(s));const savedTheme=localStorage.getItem("gameverse-theme") as Theme|null;if(savedTheme)setTheme(savedTheme);const savedLang=localStorage.getItem("gameverse-lang") as Lang|null;if(savedLang)setLang(savedLang)}catch{}},[]);
 useEffect(()=>{fetch("/api/me").then(r=>r.json()).then(x=>{if(x?.signedIn)setAccountName(x.displayName||"Player")}).catch(()=>{})},[]);
 useEffect(()=>{localStorage.setItem("gameverse-200-favorites",JSON.stringify(favs))},[favs]);
 useEffect(()=>{localStorage.setItem("gameverse-theme",theme);localStorage.setItem("gameverse-lang",lang);document.documentElement.lang=lang;document.documentElement.dir=en?"ltr":"rtl"},[theme,lang,en]);
 useEffect(()=>{const scrollWithArrows=(e:KeyboardEvent)=>{if(e.key!=="ArrowUp"&&e.key!=="ArrowDown")return;if(e.altKey||e.ctrlKey||e.metaKey||e.shiftKey)return;const target=e.target as HTMLElement|null;if(target?.closest("input, textarea, select, [contenteditable='true'], .modalbg"))return;e.preventDefault();window.scrollBy({top:(e.key==="ArrowDown"?1:-1)*window.innerHeight*.78,behavior:"smooth"})};addEventListener("keydown",scrollWithArrows);return()=>removeEventListener("keydown",scrollWithArrows)},[]);
 const filtered=useMemo(()=>catalogGames.filter(g=>(genre==="همه"||g.genre===genre)&&(!only||favs.includes(g.id))&&`${g.title} ${g.genre} ${genreEn[g.genre]}`.toLowerCase().includes(q.toLowerCase())).sort((a,b)=>b.score-a.score),[q,genre,only,favs]);
 useEffect(()=>setVisible(20),[q,genre,only]);
 const toggle=(id:number)=>setFavs(x=>x.includes(id)?x.filter(i=>i!==id):[...x,id]);
 const launch=()=>{document.getElementById("play")?.scrollIntoView({behavior:"smooth"});setTimeout(()=>window.dispatchEvent(new Event("start-shadow-house")),450)};
 const themes:Theme[]=["purple","blue","green","orange","mono","light"];
 const webGames=useMemo(()=>[88,89,101,105,108,181].map(id=>catalogGames.find(g=>g.id===id)).filter(Boolean) as CatalogGame[],[]);
 return <main className={`site theme-${theme} ${en?"is-en":"is-fa"}`} dir={en?"ltr":"rtl"}>
  <nav><a className="brand" href="#top"><span>G</span><b>GAMEVERSE_200</b></a><div className="navlinks"><a href="#event">{en?"SPECIAL EVENT":"رویداد ویژه"}</a><a href="#web-games">{en?"GAMES ON THIS WEB":"بازی‌های این وب"}</a><a href="#catalog">{en?"TOP 200 GAMES":"۲۰۰ بازی برتر"}</a><a href="#play">{en?"NEW GAME":"بازی جدید"}</a></div><div className="navtools"><div className="theme-picker" aria-label={en?"Color theme":"تم رنگی"}>{themes.map(t=><button type="button" key={t} className={`${t} ${theme===t?"active":""}`} onClick={()=>setTheme(t)} aria-label={t==="light"?(en?"Light white theme":"تم سفید روشن"):`${t} theme`}/>)}</div><button type="button" className="lang" onClick={()=>setLang(en?"fa":"en")}>{en?"فارسی":"EN"}</button><a className="authbtn" href={accountName?"/signout-with-chatgpt?return_to=/":"/signin-with-chatgpt?return_to=/"}>{accountName?`${en?"Hi":"سلام"} ${accountName}`:(en?"SIGN IN / REGISTER":"ورود / ثبت‌نام")}</a><button type="button" className="navcta" onClick={launch}>{en?"PLAY NOW":"شروع بازی"}</button></div></nav>
  <header id="top" className="hero"><div className="herocopy"><p className="eyebrow"><i/> {en?"THE BIGGEST GAMEVERSE EDITION":"بزرگ‌ترین نسخه گیم‌ورس"}</p><h1>{en?<><span>200</span> UNFORGETTABLE<br/>WORLDS</>:<><span>۲۰۰</span> دنیای<br/>فراموش‌نشدنی</>}</h1><p>{en?"Official game covers, four-line story intros, score ranking, six color themes, and a randomized playable 3D adventure.":"تصاویر رسمی بازی‌ها، معرفی داستانی چهارخطی، رتبه‌بندی امتیازی، شش تم رنگی و یک بازی سه‌بعدی با نقشهٔ تصادفی."}</p><div className="heroBtns"><a href="#catalog">{en?"EXPLORE ALL 200":"دیدن فهرست ۲۰۰تایی"}</a><button type="button" onClick={launch}>▶ {en?"PLAY BASEMENT PROTOCOL":"بازی پروتکل زیرزمین"}</button></div><div className="facts"><span><b>{en?"200":"۲۰۰"}</b>{en?" SCORE-RANKED GAMES":" بازی رتبه‌بندی‌شده"}</span><span><b>{en?"10":"۱۰"}</b>{en?" CATEGORIES":" دسته اصلی"}</span><span><b>{en?"6":"۶"}</b>{en?" COLOR THEMES":" تم رنگی"}</span></div></div><div className="heroart" aria-hidden="true"><div className="orb">200</div><div className="tile t1">ER<small>FANTASY</small></div><div className="tile t2">CP<small>FUTURE</small></div><div className="tile t3">FH<small>RACING</small></div></div></header>
  <section id="event" className="event-section"><div className="section"><div className="event-card"><img src="images/4-fighters-last-day-1.webp" alt="4 Fighter's Last Day 1"/><div className="event-copy"><span>{en?"LIVE SPECIAL EVENT":"رویداد ویژهٔ فعال"}</span><h2>4 FIGHTER&apos;S<br/>LAST DAY 1</h2><p>{en?"Enter a world captured by robots and begin the first day of the final resistance. Download the ready-to-play Windows edition, extract it and open the game—Godot is not required. This Forward+ keyboard edition does not run on phones.":"وارد دنیایی شو که ربات‌ها آن را تسخیر کرده‌اند و روز اول آخرین مقاومت را آغاز کن. نسخهٔ آمادهٔ ویندوز را دانلود و از حالت فشرده خارج کن، سپس روی فایل بازی بزن؛ نیازی به نصب Godot نیست. این نسخه با رندر Forward+ و کنترل کیبورد ساخته شده و روی گوشی اجرا نمی‌شود."}</p><div className="event-meta"><b>FORWARD+</b><b>WINDOWS 10/11</b><b>{en?"PC ONLY · NOT MOBILE":"فقط کامپیوتر · غیرقابل اجرا روی گوشی"}</b><b>{en?"NO GODOT REQUIRED":"بدون نیاز به GODOT"}</b></div><div className="event-downloads"><a href="https://github.com/hadadnejadhirad-commits/gameverse_200/releases/download/4-fighters-last-day-1/4-fighters-last-day-1-windows.zip">{en?"DOWNLOAD FOR WINDOWS ↓":"دانلود نسخهٔ ویندوز ↓"}</a><a href="https://github.com/hadadnejadhirad-commits/gameverse_200/releases/download/4-fighters-last-day-1/4-fighters-last-day-1-project.zip">{en?"DOWNLOAD GODOT PROJECT ↓":"دانلود پروژهٔ GODOT ↓"}</a><a href="https://github.com/hadadnejadhirad-commits/gameverse_200/releases/download/4-fighters-last-day-1/4-fighters-last-day-1-music-pack.zip">{en?"DOWNLOAD MUSIC PACK ↓":"دانلود بستهٔ آهنگ‌ها ↓"}</a></div></div></div></div></section>
  <section id="catalog" className="section catalog"><div className="sectionhead"><div><p className="eyebrow"><i/> {en?"RANKED BY SCORE":"مرتب‌شده براساس امتیاز"}</p><h2>{en?"200 top & popular games":"۲۰۰ بازی برتر و محبوب"}</h2></div><p>{en?"All games are ranked from the highest score down, with original artwork and a four-line story introduction.":"همهٔ بازی‌ها از بالاترین امتیاز به پایین مرتب شده‌اند و هرکدام پوستر اختصاصی و معرفی داستانی چهارخطی دارند."}</p></div><div className="tools"><label><span>⌕</span><input value={q} onChange={e=>setQ(e.target.value)} placeholder={en?"Search by name or genre...":"نام یا سبک بازی را جست‌وجو کن..."}/></label><button type="button" className={only?"on":""} onClick={()=>setOnly(!only)}>♥ {en?"Favorites":"علاقه‌مندی‌ها"} ({favs.length.toLocaleString(en?"en-US":"fa-IR")})</button></div><div className="genres">{catalogGenres.map(x=><button type="button" key={x} className={genre===x?"on":""} onClick={()=>setGenre(x)}>{en?genreEn[x]:x}</button>)}</div><div className="count"><b>{filtered.length.toLocaleString(en?"en-US":"fa-IR")}</b> {en?"games found":"بازی پیدا شد"}<i/></div><div className="grid">{filtered.slice(0,visible).map(g=><Card key={g.id} g={g} lang={lang} fav={favs.includes(g.id)} toggle={()=>toggle(g.id)} open={()=>setSelected(g)}/>)}</div>{visible<filtered.length&&<button type="button" className="more" onClick={()=>setVisible(x=>x+20)}>{en?"SHOW 20 MORE GAMES ↓":"نمایش ۲۰ بازی بعدی ↓"}</button>}</section>
  <section id="play" className="play"><div className="section"><div className="sectionhead"><div><p className="eyebrow"><i/> {en?"NEW ORIGINAL GAME":"بازی جدید"}</p><h2>{en?"Basement Protocol":"پروتکل زیرزمین"} <em>3D</em></h2></div><p>{en?"A first-person 3D mission with a working elevator, basement, rooms, randomized layout and three access cards.":"یک مأموریت سه‌بعدی اول‌شخص با آسانسور فعال، زیرزمین، اتاق‌های مختلف، نقشهٔ تصادفی و سه کارت دسترسی."}</p></div><div className="safe">{en?"This game has a spooky atmosphere but contains no graphic or disturbing scenes.":"این بازی فضای رازآلود دارد، اما صحنهٔ خشن یا دلخراش ندارد."}</div><ShadowHouse lang={lang} playerName={accountName||"Raven-7"}/><div className="features"><div><span>⇅</span><b>{en?"Working elevator":"آسانسور فعال"}</b><p>{en?"Travel between two floors":"رفت‌وآمد بین دو طبقه"}</p></div><div><span>▦</span><b>{en?"Randomized map":"نقشهٔ متغیر"}</b><p>{en?"A different layout each run":"چیدمان تازه در هر بار بازی"}</p></div><div><span>⛶</span><b>{en?"Fullscreen mode":"حالت تمام‌صفحه"}</b><p>{en?"Desktop and mobile controls":"مناسب کامپیوتر و موبایل"}</p></div><div><span>♛</span><b>{en?"Top record":"ثبت رکورد"}</b><p>{en?"Signed-in player name":"نام بازیکن واردشده"}</p></div></div></div></section>
  <section id="web-games" className="section web-games"><div className="sectionhead"><div><p className="eyebrow"><i/> {en?"ROTATING WEB PICKS":"انتخاب‌های دوره‌ای"}</p><h2>{en?"Games on this web":"بازی‌های این وب"}</h2></div><p>{en?"Use Download Game to open each title's official Steam download page.":"روی «دانلود بازی» بزن تا صفحهٔ رسمی دانلود همان بازی در Steam باز شود."}</p></div><div className="web-grid">{webGames.map(g=><article className="web-game" key={g.id}><img src={g.image} alt={g.title}/><div className="web-game-info"><span dir="ltr">{g.title}</span><b>★ {g.score}</b><div><button type="button" onClick={()=>setSelected(g)}>{en?"DETAILS":"جزئیات"}</button><a className="download-game" href={g.downloadUrl} target="_blank" rel="noreferrer" aria-label={`${en?"Download":"دانلود"} ${g.title}`}>⬇ {en?"DOWNLOAD GAME":"دانلود بازی"}</a></div></div></article>)}</div></section>
  <footer><a className="brand" href="#top"><span>G</span><b>GAMEVERSE_200</b></a><p>{en?"200 games, one shadowy house, endless adventures.":"۲۰۰ بازی، یک خانه تاریک و بی‌نهایت ماجراجویی."}</p><small>© 2026</small></footer>
  {selected&&<div className="modalbg" onMouseDown={()=>setSelected(null)}><div className="modal" onMouseDown={e=>e.stopPropagation()}><button type="button" className="close" onClick={()=>setSelected(null)}>×</button><div className="modalposter" style={{"--c1":selected.palette[0],"--c2":selected.palette[1]} as React.CSSProperties}><strong>{selected.title.split(/\s+/).slice(0,2).map(x=>x[0]).join("")}</strong><span dir="ltr">{selected.title}</span><b>{en?"Rank":"رتبه"} {selected.id.toLocaleString(en?"en-US":"fa-IR")}</b></div><div className="modalcopy"><p className="eyebrow"><i/> {en?"FULL GAME PROFILE":"معرفی کامل بازی"}</p><h2 dir="ltr">{selected.title}</h2><div className="score">★ {selected.score.toLocaleString(en?"en-US":"fa-IR")} <small>{en?"EDITOR SCORE":"امتیاز تحریریه"}</small></div><p>{en?"A memorable title with distinctive art direction, thoughtful level design, and engaging gameplay. It earned a place in the GAMEVERSE_200 selection.":`${selected.description} این اثر به‌خاطر هویت بصری، طراحی مراحل و تجربه‌ای که در سبک خودش ارائه می‌دهد در فهرست ۲۰۰ انتخاب گیم‌ورس قرار گرفته است.`}</p><div className="detail"><span><small>{en?"GENRE":"سبک"}</small><b>{en?genreEn[selected.genre]:selected.genre}</b></span><span><small>{en?"MODE":"حالت بازی"}</small><b>{en?"Multiple modes":selected.mode}</b></span><span><small>{en?"ENTRY LEVEL":"درجه ورود"}</small><b>{en?"Selected title":selected.difficulty}</b></span><span><small>{en?"RANK":"رتبه مجموعه"}</small><b>{selected.id.toLocaleString(en?"en-US":"fa-IR")}</b></span></div><button type="button" className={favs.includes(selected.id)?"save on":"save"} onClick={()=>toggle(selected.id)}>{favs.includes(selected.id)?(en?"♥ SAVED":"♥ ذخیره شده"):(en?"♡ ADD TO FAVORITES":"♡ افزودن به علاقه‌مندی‌ها")}</button></div></div></div>}
 </main>
}
